version: 2
updates:
  - package-ecosystem: "pip"
    directory:"/requirements"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    ignore:
      - dependency-name: "grpcio"
    reviewers: 
      - "acohen-work"
      - "zlilek-work"  

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
    reviewers: 
      - "acohen-work"  
      - 'zlilek-work"'
