version: 2
registries:
  privatepypi:
    type: python-index
    url: pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/
    token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}

updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    registries:
      - privatepypi
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    ignore:
      - dependency-name: "grpcio"
      - dependency-name: "ansys-turbogrid-api"
    reviewers: 
      - "acohen-work"
      - "zlilek-work"  

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
    reviewers: 
      - "acohen-work"  
      - "zlilek-work"
