version: 2
#registries:
#  python-azure:
#    type: python-index
#    url: https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/
#    token: ${{ secrets.PYANSYS_PYPI_PRIVATE_READ_PAT }}

updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    #registries:
    #  - python-azure
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    ignore:
      - dependency-name: "ansys-turbogrid-api"
    reviewers: 
      - "acohen-work"
      - "zlilek-work"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
    reviewers: 
      - "acohen-work"  
      - "zlilek-work"
