- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: FFD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: release
  description: Anything related to an incoming release
  color: ffffff

- name: "autorelease: pending"
  description: Autorelease pending with release-please - the initial state of the Release PR before it is merged
  color: 00a6ed

- name: "autorelease: snapshot"
  description: Autorelease snapshot with release-please - special state for snapshot version bumps
  color: ffb02e

- name: "autorelease: tagged"
  description: Autorelease tagged with release-please - the Release PR has been merged and the release has been tagged in GitHub
  color: cdc4d6
