name: Release Private

on:
    workflow_dispatch: 

env:
    MAIN_PYTHON_VERSION: '3.10'
    LIBRARY_NAME: 'ansys-turbogrid-core'
    PIP_INDEX_URL: "https://${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"
    POETRY_HTTP_BASIC_PYANSYS_PRIVATE_PYPI_USERNAME: "PAT"
    POETRY_HTTP_BASIC_PYANSYS_PRIVATE_PYPI_PASSWORD: ${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}  

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true 

jobs:
    build-library:
        name: Build library
        runs-on: ubuntu-latest
        steps:
        - name: "Build library source and wheel artifacts"
          uses: ansys/actions/build-library@v8
          with:
              library-name: ${{ env.LIBRARY_NAME }}
              python-version: ${{ env.MAIN_PYTHON_VERSION }}

    release:
        name: Release project
        runs-on: ubuntu-latest
        needs: [build-library]
        steps:
            - name: "Release to the private PyPI repository"
              uses: ansys/actions/release-pypi-private@v8
              with:
                  library-name: ${{ env.LIBRARY_NAME }}
                  twine-username: "__token__"
                  twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}